# ===================
# « Project section »
# ===================

[project]
name = "python_modules"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "mypy>=2.3.0",
    "pydantic>=2.13.4",
    "ruff>=0.16.2",
]

# =================
# « Tools section »
# =================

# My Ruff Config:
[tool.ruff]
indent-width = 4
line-length = 88
respect-gitignore = true
target-version = "py314"
extend-exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
]
show-fixes = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.ruff.lint]
preview = true
select = ["ALL"]
extend-select = []
ignore = [
    "T201",
    "D",
    "DOC",
    "CPY",
    "SLF001",
    "RUF201",
    "PLR6301",
    "PLR0913",
    "PLR0917",
    "PLC0415",
    "PTH",
    "ANN401",
    "FBT",
    "S311",
    "TID252",
    "SIM115",
]
fixable = []
unfixable = []


[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"m0/**/*.py" = ["INP001"]

# 42 Tools Config:
[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
extend-exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
]
count = true
statistics = true
show-source = true
per-file-ignores = [
    "__init__.py:F401",
]

[tool.mypy]
python_version = "3.14"
strict = true
exclude = [
    ".venv/",
    ".git/",
    "build/",
    "dist/",
    "__pycache__/",
    ".ruff_cache"
]
