# ===================
# « Project section »
# ===================

[project]
name = "python_modules"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "flake8>=7.3.0",
    "flake8-pyproject>=1.2.4",
    "mypy>=2.3.0",
    "ruff>=0.16.2",
    "ty>=0.0.69",
    # exclude afterwards
]

# =================
# « Tools section »
# =================

# My TY config:
[tool.ty]

[tool.ty.analysis]


# My Ruff Config:
[tool.ruff]
indent-width = 4
line-length = 79
respect-gitignore = true
target-version = "py314"
extend-exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
]
show-fixes = true
#output-format = "grouped"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.ruff.lint]
preview = true
select = ["ALL"]
extend-select = [
    "E",
    "F",
    "W",
    "I",
    "B",
    "N",
    "C90",
]

ignore = [
    "D",
    "DOC",
    "RUF",
    "CPY",
    "SIM",
    "TID",
    "S",
    "FBT",
    "PL",
    "T20",
    "PGH",
    "COM"
]
fixable = ["ALL"]
unfixable = ["T20", "PGH"]


[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.per-file-ignores]
"m0/**/*.py" = ["INP001"]
"m2/**/*.py" = ["SIM115", "PTH"]
"m4/**/*.py" = ["SIM115", "PTH"]
"m5/**/*.py" = ["ANN401"]
"m8/**/*.py" = ["PTH"]
"m10/**/*.py"=["FURB", "C4", "TC", "ANN"]


# 42 Tools Config:

[tool.flake8]
max-line-length = 79
extend-ignore = ["E203", "W503"]
extend-exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
]
count = true
statistics = true
show-source = true
per-file-ignores = [
    "__init__.py:F401",
]

[tool.mypy]
python_version = "3.14"
exclude = [
    ".venv/",
    ".git/",
    "build/",
    "dist/",
    "__pycache__/",
    ".ruff_cache"
]
