# ===================
# « Project section »
# ===================

[project]
name = "python_modules"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "requests>=2.34.2",
]

# =================
# « Tools section »
# =================

# My TY config:
[tool.ty]


# My Ruff Config:
[tool.ruff]
indent-width = 4
line-length = 79
respect-gitignore = true
target-version = "py314"
extend-exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
]
show-fixes = true
output-format = "grouped"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.ruff.lint]
preview = true
select = ["ALL"]
extend-select = []

ignore = ["T20", "RUF"]
fixable = ["ALL"]
unfixable = ["T20"]


[tool.ruff.lint.mccabe]
max-complexity = 10


# 42 Tools Config:

[tool.flake8]
max-line-length = 79
extend-ignore = ["E203", "W503"]
extend-exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
]
count = true
statistics = true
show-source = true

[tool.mypy]
python_version = "3.14"
strict = true
exclude = [
    ".venv/",
    ".git/",
    "build/",
    "dist/",
    "__pycache__/",
    ".ruff_cache"
]
